config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages, except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
  # presence: true => 必須入力
  validates :name, length: {maximum: 20}, presence: true
  validates :body, length: {minimum: 2, maximum: 30 }, presence: true
  AGE_GE = 0
  AGE_LE = 100
  validates :age,  numericality: { only_integer: true, greater_than_or_equal_to: AGE_GE, less_than_or_equal_to: AGE_LE }, allow_blank: true, presence: false

  def get_age
    self.age ? self.age  : "年齢不詳"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def index
    @messages = Message.all
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを投稿しました'
    else
      @messages = Message.all
      flash.now[:alert] = "メッセージの投稿に失敗しました"
      render 'index'
    end   
  end
  
  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end

  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar">
      <div class="container">
        <div class="navbar-header">
          <h1><a class="navbar-brand" href="#">Message Board</a></h1>
        </div>
      </div>
    </nav>
    <div class=container-fluid>
      <div class="container">
        <% if notice %>
          <div class="alert alert-success">
            <%= notice %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/messages/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ入力欄
  </div>
  <div class="panel-body">
    <div class="form-horizontal" role="form">
      <%= form_for(@message) do |f| %>
        <% if @message.errors.present? %>
          <div class="alert alert-danger">
            <%= alert %>
            <ul>
              <% @message.errors.full_messages.each do |full_message| %>
                <li>
                  <%= full_message %>
                </li>
              <% end %> 
            </ul>
          </div> 
        <% end %>
        
      <div class="form-group">
        <%= f.label "名前", :class => "col-sm-1 control-label" %>
        <div class="col-sm-3">
          <%= f.text_field :name, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "年齢", :class => "col-sm-1 control-label" %>
        <div class="col-sm-3">
          <%= f.number_field :age, :class => "form-control", min: Message::AGE_GE, max: Message::AGE_LE %>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label "本文", :class => "col-sm-1 control-label" %>
        <div class="col-sm-7">
          <%= f.text_area :body, :class => "form-control" %>
        </div>
      </div>
      
      <div class="col-sm-2">
        <%= f.submit '送信', class: "btn btn-sm btn-primary btn-block" %>
      </div>
  
      <% end %>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    メッセージ一覧
  </div>
  <div class="panel-body">
    <% @messages.each do |message| %>
      <span class="label label-info"><%= message.name %>(<%= message.get_age %>)</span>
        <%= message.body %>
        ( <%= link_to "edit" , edit_message_path(message) %> | 
        <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>)
      <br>
    <% end %>
</div>
</div>

<%= render 'form' %>